  name: Versal-STAFF
  main: linareslinares\Loader
  api: 5.0.0
  version: 1.0
  author: "LinaresFunado [YT: @linareslinares ]"
  description: "Versal-STAFF by LinaresFunado"

  permissions:
    versalstaff.cmd:
      default: op
    versalstaff.report:
      default: true