name: Notify

on: [push]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"**New commit in repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})\n\n**Commit:** ${{ github.event.head_commit.message }}\n**Author:** ${{ github.event.head_commit.author.name }}\n[View Repository](https://github.com/${{ github.repository }})\"}" \
             $DISCORD_WEBHOOK_URL
