name: Notify

on: [push]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"New commit in repository: ${{ github.repository }}\n\nCommit message: ${{ github.event.head_commit.message }}\nAuthor: ${{ github.event.head_commit.author.name }}\nRepository URL: https://github.com/${{ github.repository }}\"}" \
             $DISCORD_WEBHOOK_URL
